### PR TITLE
SDK-193 - Java - empty optionals being set to null when constructing …

### PR DESCRIPTION
**Pull request by jason-womack**
…objects from JSON responses

---
This change is [Reviewable](https://reviewable.io/reviews/solidfire/jsvcgen/58)

### CODE REVIEW

**Comment by ahaid** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[jsvcgen-client-java/src/main/java/com/solidfire/jsvcgen/serialization/OptionalAdaptorUtils.java, line 13 \[r1\]](https://reviewable.io:443/reviews/solidfire/jsvcgen/58#-KHa7N8zyaTjM7C9Z-t0:-KHa7N9-2C4htyx3plpR:-1667369909) ([raw file](https://github.com/solidfire/jsvcgen/blob/7f86c29f6df30baa2eb8f87960107131ef5f7dcf/jsvcgen-client-java/src/main/java/com/solidfire/jsvcgen/serialization/OptionalAdaptorUtils.java#L13)):*
> ```Java
>  */
> public class OptionalAdaptorUtils {
>     public static <T> T initializeAllNullOptionalFieldsAsEmpty(final T obj) {
> ```

Could you add some comments above each of these methods that state what its purpose is?

---

*[jsvcgen-client-java/src/test/java/com/solidfire/jsvcgen/JavaClasses.java, line 1 \[r1\]](https://reviewable.io:443/reviews/solidfire/jsvcgen/58#-KHa7j-rlSv-Vz5A6hB-:-KHa7j-sAwxwa9PC2P_C:235704869) ([raw file](https://github.com/solidfire/jsvcgen/blob/7f86c29f6df30baa2eb8f87960107131ef5f7dcf/jsvcgen-client-java/src/test/java/com/solidfire/jsvcgen/JavaClasses.java#L1)):*
> ```Java
> package com.solidfire.jsvcgen;
> ```

It would be more appropriate to set this package to com.solidfire.jsvcgen.test so these classes don't get pulled in when com.solidfire.jsvcgen is referenced.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/solidfire/jsvcgen/58)*

**Comment by jason-womack** [comment]
Our numbers went down because none of the instrumented reports were being transmited to codecov.io, so it was reporting as 100%.  These numbers are accurate.

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **48.79%**
> > Merging [#58][cc-pull] into [develop][cc-base-branch] will increase coverage by **-51.21%**
> 
> 1. 12 files (not in diff) in `...fire/jsvcgen/codegen` were created. [more](https://codecov.io/gh/solidfire/jsvcgen/commit/33a93fac39043c1127e66304f830391c59a6e27d/changes?src=pr#6A73766367656E2F7372632F6D61696E2F7363616C612F636F6D2F736F6C6964666972652F6A73766367656E2F636F646567656E)
> 1. 12 files (not in diff) in `...idfire/jsvcgen/model` were created. [more](https://codecov.io/gh/solidfire/jsvcgen/commit/33a93fac39043c1127e66304f830391c59a6e27d/changes?src=pr#6A73766367656E2D636F72652F7372632F6D61696E2F7363616C612F636F6D2F736F6C6964666972652F6A73766367656E2F6D6F64656C)
> 1. 2 files (not in diff) in `...om/solidfire/jsvcgen` were created. [more](https://codecov.io/gh/solidfire/jsvcgen/commit/33a93fac39043c1127e66304f830391c59a6e27d/changes?src=pr#6A73766367656E2D636F72652F7372632F6D61696E2F7363616C612F636F6D2F736F6C6964666972652F6A73766367656E)
> 1. 2 files (not in diff) in `...svcgen/serialization` were created. [more](https://codecov.io/gh/solidfire/jsvcgen/commit/33a93fac39043c1127e66304f830391c59a6e27d/changes?src=pr#6A73766367656E2D636C69656E742D6A6176612F7372632F6D61696E2F6A6176612F636F6D2F736F6C6964666972652F6A73766367656E2F73657269616C697A6174696F6E)
> 1. 5 files (not in diff) in `...dfire/jsvcgen/client` were created. [more](https://codecov.io/gh/solidfire/jsvcgen/commit/33a93fac39043c1127e66304f830391c59a6e27d/changes?src=pr#6A73766367656E2D636C69656E742D6A6176612F7372632F6D61696E2F6A6176612F636F6D2F736F6C6964666972652F6A73766367656E2F636C69656E74)
> 
> ```diff
> @@           develop        #58   diff @@
> =========================================
>   Files            0         39     +39   
>   Lines            0       1736   +1736   
>   Methods          0          0           
>   Messages         0          0           
>   Branches         0        420    +420   
> =========================================
> + Hits             0        847    +847   
> - Misses           0        889    +889   
>   Partials         0          0           
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [f685d3f...33a93fa][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/solidfire/jsvcgen/branch/develop?src=pr
> [cc-compare]: https://codecov.io/gh/solidfire/jsvcgen/compare/f685d3f84868e13439aa2243bc95bd16a5d8f27f...33a93fac39043c1127e66304f830391c59a6e27d
> [cc-pull]: https://codecov.io/gh/solidfire/jsvcgen/pull/58?src=pr</details>


---

Review status: 5 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[jsvcgen-client-java/src/main/java/com/solidfire/jsvcgen/serialization/OptionalAdaptorUtils.java, line 13 \[r1\]](https://reviewable.io:443/reviews/solidfire/jsvcgen/58#-KHa7N8zyaTjM7C9Z-t0:-KHfAqFK1Um8_dXN4rTs:-1907931527) ([raw file](https://github.com/solidfire/jsvcgen/blob/7f86c29f6df30baa2eb8f87960107131ef5f7dcf/jsvcgen-client-java/src/main/java/com/solidfire/jsvcgen/serialization/OptionalAdaptorUtils.java#L13)):*
<details><summary><i>Previously, ahaid (Adam Haid) wrote…</i></summary>
> Could you add some comments above each of these methods that state what its purpose is?</details>
Included JavaDoc at the top of each method.

---

*[jsvcgen-client-java/src/test/java/com/solidfire/jsvcgen/JavaClasses.java, line 1 \[r1\]](https://reviewable.io:443/reviews/solidfire/jsvcgen/58#-KHa7j-rlSv-Vz5A6hB-:-KHfAEkHOIwSuarxIwOE:1253827744) ([raw file](https://github.com/solidfire/jsvcgen/blob/7f86c29f6df30baa2eb8f87960107131ef5f7dcf/jsvcgen-client-java/src/test/java/com/solidfire/jsvcgen/JavaClasses.java#L1)):*
<details><summary><i>Previously, ahaid (Adam Haid) wrote…</i></summary>
> It would be more appropriate to set this package to com.solidfire.jsvcgen.test so these classes don't get pulled in when com.solidfire.jsvcgen is referenced.</details>
Since these packages are under the test source, it would never be included in the main source.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/solidfire/jsvcgen/58#-:-KHfAVy1UgbZ3A9T_NGO:1655978022)*

**Comment by jason-womack** [comment]
Reviewed 1 of 10 files at r1, 6 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/solidfire/jsvcgen/58)*

**Comment by jason-womack** [comment]
Reviewed 4 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/solidfire/jsvcgen/58)*

**Pull request merged**
